@apiurl_1 = http://localhost:8000/api
@apiurl_2 = https://rcp-laravel-api.herokuapp.com/api
@token = {{login.response.body.$.data.token}}

###
GET {{apiurl_1}}
Content-Type: application/json

###
# @name login
POST {{apiurl_1}}/login
Content-Type: application/json

{  
    "email": "recep_1@gmail.com",
    "password": "123456"
}

###
POST {{apiurl_1}}/register
Content-Type: application/json 

{ 
    "name" :"Recep 1", 
    "email": "recep_1@gmail.com",
    "password": "123456",
    "confirm_password": "123456"
}

###
GET {{apiurl_1}}/animals
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{apiurl_1}}/animals/2
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{apiurl_1}}/animals
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "ear_no": "TR123",
    "name": "test",
    "gender": "Dişi"
}

###
PUT {{apiurl_1}}/animals/2
Content-Type: application/json
Authorization: Bearer {{token}}

{  
     "ear_no": "TR1234"
}

###
DELETE  {{apiurl_1}}/animals/1
Content-Type: application/json
Authorization: Bearer {{token}}